version: '3.7'

services:
  omnaeskuvaultwebapi-db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - '50542:1433'
    environment:
      - DB_USER=SA
      - SA_PASSWORD=#localDockerPassword#
      - DB_CONTAINER_NAME=dev_omnaeskuvaultwebapi
      - ACCEPT_EULA=Y
    volumes:
      - omnaeskuvaultwebapi-data:/var/lib/sqlserver/data

  jaeger:
    image: jaegertracing/all-in-one:latest
#    port mappings: https://www.jaegertracing.io/docs/1.32/getting-started/
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

        
volumes:
  # compose volumes marker - do not delete
  omnaeskuvaultwebapi-data:
