// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmnaeSkuVaultWebApi.Databases;

#nullable disable

namespace OmnaeSkuVaultWebApi.Migrations
{
    [DbContext(typeof(FinanceServiceDbContext))]
    [Migration("20220819170821_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OmnaeSkuVaultWebApi.Domain.SkuVaultAccounts.SkuVaultAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsVendor")
                        .HasColumnType("bit")
                        .HasColumnName("is_vendor");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on");

                    b.Property<int>("SkuVaultId")
                        .HasColumnType("int")
                        .HasColumnName("sku_vault_id");

                    b.Property<string>("SkuVaultTokenId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sku_vault_token_id");

                    b.HasKey("Id")
                        .HasName("pk_sku_vault_accounts");

                    b.ToTable("sku_vault_accounts", (string)null);
                });

            modelBuilder.Entity("OmnaeSkuVaultWebApi.Domain.SkuVaultTokens.SkuVaultToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit")
                        .HasColumnName("is_revoked");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_on");

                    b.Property<string>("SkuVaultCompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sku_vault_company_id");

                    b.Property<string>("TenantToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tenant_token");

                    b.Property<string>("UserToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_token");

                    b.HasKey("Id")
                        .HasName("pk_sku_vault_tokens");

                    b.ToTable("sku_vault_tokens", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
